#!/usr/bin/env bash
set -Eeuo pipefail

COMPOSE_FILE="docker-compose.yaml"
ENV_FILE=".env"
BASE_PORT=9000
MAX_LABS=10

echo "--------------------------------------------------"
echo "Deepfield Remote Management Docker Client"
echo "Multi-lab setup"
echo "--------------------------------------------------"
echo

while true; do
    read -r -p "How many labs do you want to configure? [1-${MAX_LABS}]: " LAB_COUNT
    if [[ "${LAB_COUNT}" =~ ^[0-9]+$ ]] && (( LAB_COUNT >= 1 && LAB_COUNT <= MAX_LABS )); then
        break
    fi
    echo "Please enter a number from 1 to ${MAX_LABS}."
done

echo
echo "Port allocation:"
for ((i=1; i<=LAB_COUNT; i++)); do
    base=$((BASE_PORT + (i - 1) * 3))
    echo "  Lab ${i}: client=${base}, SSH=$((base + 1)), UI=$((base + 2))"
done
echo

# Back up generated files if present.
timestamp="$(date +%Y%m%d-%H%M%S)"
for f in "${ENV_FILE}" "${COMPOSE_FILE}"; do
    if [[ -f "${f}" ]]; then
        cp -p "${f}" "${f}.bak-${timestamp}"
        echo "Backed up ${f} -> ${f}.bak-${timestamp}"
    fi
done

cat > "${ENV_FILE}" <<EOF
# Generated by setup.sh on $(date)
LAB_COUNT=${LAB_COUNT}
OPS_USER=ops
MONITOR_INTERVAL=5
EOF

AUTHORIZED_KEYS_FILE="authorized_keys"

echo
echo "All configured lab public keys will be combined into one shared"
echo "authorized_keys file and mounted into every lab container."
echo
echo "Enter public-key file paths one at a time."
echo "Press ENTER with no path when finished."
echo

tmp_keys="$(mktemp)"
trap 'rm -f "${tmp_keys}"' EXIT

key_count=0
while true; do
    read -r -p "Public key path [$((key_count + 1))] (ENTER when done): " key_path

    if [[ -z "${key_path}" ]]; then
        if (( key_count == 0 )); then
            echo "At least one public key is required."
            continue
        fi
        break
    fi

    if [[ "${key_path}" == "~/"* ]]; then
        key_path="${HOME}/${key_path#~/}"
    fi

    if [[ ! -s "${key_path}" ]]; then
        echo "ERROR: Public key file does not exist or is empty: ${key_path}"
        continue
    fi

    cat "${key_path}" >> "${tmp_keys}"
    echo >> "${tmp_keys}"
    key_count=$((key_count + 1))
    echo "Added: ${key_path}"
done

# Remove blank lines and duplicate identical public-key lines.
awk 'NF && !seen[$0]++' "${tmp_keys}" > "${AUTHORIZED_KEYS_FILE}"

unique_key_count="$(wc -l < "${AUTHORIZED_KEYS_FILE}" | tr -d ' ')"

if [[ "${unique_key_count}" -eq 0 ]]; then
    echo "ERROR: No valid public keys were written."
    exit 1
fi

chmod 0600 "${AUTHORIZED_KEYS_FILE}"

echo
echo "Created shared ${AUTHORIZED_KEYS_FILE} with ${unique_key_count} unique key(s)."
echo "The same key set will be trusted by all ${LAB_COUNT} lab containers."
echo

cat > "${COMPOSE_FILE}" <<'EOF'
# Generated by setup.sh. Re-run setup.sh to change the number of labs.
services:
EOF

for ((i=1; i<=LAB_COUNT; i++)); do
    base=$((BASE_PORT + (i - 1) * 3))
    ssh_port=$((base + 1))
    ui_port=$((base + 2))

    cat >> "${COMPOSE_FILE}" <<EOF
  lab${i}:
    build:
      context: .
      dockerfile: Dockerfile
    image: remote-management-client:latest
    container_name: reverse-ssh-client-lab${i}
    restart: unless-stopped

    ports:
      # Lab ${i}: Python server connects to host port ${base}.
      - "${base}:9000"
      # Reverse forwards requested by Lab ${i}.
      - "${ssh_port}:${ssh_port}"
      - "${ui_port}:${ui_port}"

    environment:
      OPS_USER: "\${OPS_USER:-ops}"
      LAB_NAME: "lab${i}"
      REMOTE_SSH_PORT: "${ssh_port}"
      REMOTE_UI_PORT: "${ui_port}"
      MONITOR_INTERVAL: "\${MONITOR_INTERVAL:-5}"

    volumes:
      - "./authorized_keys:/config/authorized_keys:ro"
      - lab${i}-ssh-host-keys:/etc/ssh/host-keys

    healthcheck:
      test: ["CMD-SHELL", "sshd -t && pgrep -x sshd >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

EOF
done

cat >> "${COMPOSE_FILE}" <<'EOF'
volumes:
EOF

for ((i=1; i<=LAB_COUNT; i++)); do
    echo "  lab${i}-ssh-host-keys:" >> "${COMPOSE_FILE}"
done

echo
echo "Generated:"
echo "  ${ENV_FILE}"
echo "  ${COMPOSE_FILE}"
echo
echo "============================================================"
echo "Remote Management Multi-Lab Configuration"
echo "============================================================"

LABS_FILE="LABS.txt"

# Write the same useful deployment map to LABS.txt.
{
    echo "============================================================"
    echo "Remote Management Multi-Lab Configuration"
    echo "Generated: $(date)"
    echo "============================================================"

    for ((i=1; i<=LAB_COUNT; i++)); do
        base=$((BASE_PORT + (i - 1) * 3))
        ssh_port=$((base + 1))
        ui_port=$((base + 2))

        echo
        echo "Lab ${i}:"
        echo "  Authorized keys           : shared authorized_keys (${unique_key_count} unique key(s))"
        echo "  Python server tunnel port : ${base}"
        echo "  Remote SSH access         : ${ssh_port}"
        echo "  Remote HTTPS access       : ${ui_port}"
        echo
        echo "  Configure the Python server with:"
        echo "    CLIENT_SSH_TUNNEL_PORT=${base}"
        echo
        echo "  Connect through the Docker host:"
        echo "    ssh -p ${ssh_port} support@<docker-host>"
        echo "    https://<docker-host>:${ui_port}"
    done

    echo
    echo "============================================================"
    echo "Docker commands"
    echo "============================================================"
    echo
    echo "Start the Docker clients:"
    echo "  sudo docker-compose build --no-cache"
    echo "  sudo docker-compose up -d"
    echo "  sudo docker-compose ps"
    echo
    echo "View logs:"
    for ((i=1; i<=LAB_COUNT; i++)); do
        echo "  sudo docker-compose logs -f lab${i}"
    done
    echo
    echo "Stop all labs:"
    echo "  sudo docker-compose down"
    echo
    echo "For Docker Compose v2, use 'docker compose' instead of 'docker-compose'."
    echo "============================================================"
} > "${LABS_FILE}"

# Print the deployment map to screen too.
cat "${LABS_FILE}"

echo
echo "Configuration also saved to:"
echo "  ${LABS_FILE}"
